import { SessionProvider } from "next-auth/react";
import AuthProvider from "@/components/AuthProvider"; // Adjust path if AuthProvider is elsewhere
import ClientProviders from "@/components/ClientProviders"; // Import the new ClientProviders component
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "My App", // Replace with your app's title
  description: "Generated by create next app", // Replace with your app's description
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClientProviders>
          {" "}
          {/* Use ClientProviders to wrap children */}
          {children}
        </ClientProviders>
      </body>
    </html>
  );
}
